### PR TITLE
PINOUT diagram Updated in readme and in image file

### PR DESCRIPTION
**Pull request by ARX-0**
Updated Readme.md {included the new pinout diagram}
and included the pinout diagram png in the images folder 
:)

### CODE REVIEW

**Comment by yathAg** [comment]
Hi, thank you for the contribution 

There are a couple of changes before I can accept it to this repository. 

- If possible, please match the color scheme to the pinout image.
- include different color schemes for timer1 and timer 2
- mention the voltage ( no need for `vdd`)
- use black for gnd
- don't use a triangular layout for pins on the left. Please make them vertically aligned in columns

**Comment by ARX-0** [comment]
requested changes were made....(pull request was updated
 please check the below image 
vsd pinout image
 
if satisfied proceed further or tell me where to improve :)

**Comment by yathAg** [comment]
Hi 

- In the legend, change `SWDIO` to `SWD`
- Include pin name in legend
- Use one new color for `RX` and `TX` on the right. For this, create a new legend called **Programmer UART**

- You have worked hard, and I appreciate the effort. Let's make it perfect. Align the left ones perfectly; there are still slight alignment issues. If u need help with that, I can do them in the draw.io project

**Comment by ARX-0** [comment]
Can you please take care of the alignment and i will take care of the rest ... I do agree and i want it to be perfect too ... I will update this pull request in another 12hours (provided that i am in a different timezone)

**Comment by ARX-0** [comment]
Update:-

VSD_PINOUT_UPDATE2

made the requested changes 
if any allignment issues feel free to correct it :)

**Comment by ARX-0** [comment]
the new pull request has been made 
vsd pinout image

vsd pinout image update final

with the two images being the old and the updated one respectively :)

**Pull request merged**
